### PR TITLE
Fix "Remember are humans"

### PR DESCRIPTION
**Pull request by hsablonniere**
I have a doubt about this since english is not my mother tongue but this sentence felt weird.

### CODE REVIEW

**Comment by remy** [comment]
👍

**Comment by hsablonniere** [comment]
Lol, fixed, merged and published before I finished to read the article. That's the power of content as code ;-)

**Comment by remy** [comment]
Merged from the gym too!

**Comment by hsablonniere** [comment]
BTW I found out about your edit link (next to the article title) afterwards. IMO, it could be more visible #justsayin.

**Comment by remy** [comment]
Yeah, I'm on the fence about that. I don't like it too visible because I
think it's distracting to the title, but then I don't really have a place
for it…generally agree though!

**Comment by hsablonniere** [comment]
I agree, I don't have a solution either, it's a tough problem. 🤔

**Pull request merged**
